language: java

before_install:
  - git clone -b 1.8 --single-branch https://github.com/apache/accumulo.git accumulo
  - cd accumulo
  - mvn clean install -P assemble -P docs -DskipTests -Dfindbugs.skip -Drat.skip -Dhadoop.version=2.7.2
  - cd ..
